# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_auto_20161005_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrado',
            name='cedula',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrado',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
