# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_remove_registrado_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='codigo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
