# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_auto_20161006_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_alumno', models.IntegerField()),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=60)),
                ('id_alumno', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='asig_jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='asignaturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_asignaturas', models.IntegerField()),
                ('nombre', models.CharField(max_length=60)),
                ('creditos', models.IntegerField()),
                ('numero_horas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dias', models.IntegerField()),
                ('dia', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='franja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_franja', models.IntegerField()),
                ('codigo_dias', models.ManyToManyField(to='estudiantes.dias')),
            ],
        ),
        migrations.CreateModel(
            name='hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hora', models.IntegerField()),
                ('hora', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idhorario', models.IntegerField()),
                ('codigo_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_jornada', models.IntegerField()),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='periodo_academico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pa', models.IntegerField()),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tipo', models.IntegerField()),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='registrado',
        ),
        migrations.AddField(
            model_name='horario',
            name='codigo_pa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.periodo_academico'),
        ),
        migrations.AddField(
            model_name='franja',
            name='codigo_hora',
            field=models.ManyToManyField(to='estudiantes.hora'),
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='codigo_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.tipo'),
        ),
        migrations.AddField(
            model_name='asig_jornada',
            name='codigo_asignaturas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.asignaturas'),
        ),
        migrations.AddField(
            model_name='asig_jornada',
            name='codigo_jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.jornada'),
        ),
    ]
