# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-31 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0006_auto_20161019_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='codigo_alumno',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id_alumno',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(max_length=11),
        ),
    ]
