# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0007_auto_20161031_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dias',
            name='dia',
            field=models.CharField(max_length=11),
        ),
    ]
