# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0008_auto_20161107_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dias',
            options={'ordering': ['dia']},
        ),
    ]
