from django.conf.urls import url
from .views import *
from django.conf.urls import patterns, url, include


urlpatterns=patterns('apps.estudiantes.views',
     url(r'^$',index ,name='index'),
     url(r'^listares/$', alumnolist.as_view(), name='estud_list'),
     url(r'^nuevoes/$', alumnoCreate.as_view(), name='estud_crear'),
     url(r'^editares/(?P<pk>\d+)/$', alumnoUpdate.as_view(), name='estud_edit'),
     url(r'^borrares/(?P<pk>\d+)/$', alumnoDelete.as_view(), name='estud_delete'),
     url(r'^listaras/$', asignaturalist.as_view(), name='asig_list'),
     url(r'^nuevoas/$', asignaturaCreate.as_view(), name='asig_crear'),
     url(r'^editaras/(?P<pk>\d+)/$', asignaturaUpdate.as_view(), name='asig_edit'),
     url(r'^borraras/(?P<pk>\d+)/$', asignaturaDelete.as_view(), name='asig_delete'),
     url(r'^listardi/$', diaslist.as_view(), name='dias_list'),
     url(r'^nuevodi/$', diasCreate.as_view(), name='dias_crear'),
     url(r'^editardi/(?P<pk>\d+)/$', diasUpdate.as_view(), name='dias_edit'),
     url(r'^borrardi/(?P<pk>\d+)/$', diasDelete.as_view(), name='dias_delete'),
     url(r'^listarpe/$', periodoList.as_view(), name='periodo_list'),
     url(r'^nuevope/$', periodoCreate.as_view(), name='periodo_crear'),
     url(r'^editarpe/(?P<pk>\d+)/$', periodoUpdate.as_view(), name='periodo_edit'),
     url(r'^borrarpe/(?P<pk>\d+)/$', periodoDelete.as_view(), name='periodo_delete'),
     url(r'^listarho/$', horaList.as_view(), name='hora_list'),
     url(r'^nuevoho/$', horaCreate.as_view(), name='hora_crear'),
     url(r'^editarho/(?P<pk>\d+)/$', horaUpdate.as_view(), name='hora_edit'),
     url(r'^borrarho/(?P<pk>\d+)/$', horaDelete.as_view(), name='hora_delete'),
     url(r'^nuevof/$', franja_crearview.as_view(), name='franja_crear'),
     url(r'^listarf/$', franjaList.as_view(), name='franja_list'),
     url(r'^listart/$', tipoList.as_view(), name='tipo_list'),
     url(r'^nuevot/$', tipoCreate.as_view(), name='tipo_crear'),
     url(r'^editart/(?P<pk>\d+)/$', tipoUpdate.as_view(), name='tipo_edit'),
     url(r'^borrart/(?P<pk>\d+)/$', tipoDelete.as_view(), name='tipo_delete'),
     url(r'^listarjo/$', jornadaList.as_view(), name='jornada_list'),
     url(r'^nuevojo/$', jornadaCreate.as_view(), name='jornada_crear'),
     url(r'^editarjo/(?P<pk>\d+)/$', jornadaUpdate.as_view(), name='jornada_edit'),
     url(r'^borrarjo/(?P<pk>\d+)/$', jornadaDelete.as_view(), name='jornada_delete'),
     url(r'^listaraj/$', asigjornadaList.as_view(), name='asigjornada_list'),
     url(r'^nuevoaj/$', asigjornadaCreate.as_view(), name='asigjornada_crear'),
     url(r'^editaraj/(?P<pk>\d+)/$', asigjornadaUpdate.as_view(), name='asigjornada_edit'),
     url(r'^borraraj/(?P<pk>\d+)/$', asigjornadaDelete.as_view(), name='asigjornada_delete'),
     url(r'^listarhr/$', horarioList.as_view(), name='horario_list'),
     url(r'^nuevoahr/$', horarioCreate.as_view(), name='horario_crear'),
     url(r'^editarahr/(?P<pk>\d+)/$', horarioUpdate.as_view(), name='horario_edit'),
     url(r'^borrarahr/(?P<pk>\d+)/$', horarioDelete.as_view(), name='horario_delete'),

)